### ISSUE TITLE
linting fails

### ISSUE THREAD

**Issue by utvk** [Dindaleon/hapi-react-starter-kit#13]
Hi

wanted to test out project, but seems to have many lint errors, missing semicolons etc and only throws. Should i clean up and make a pr?

**Comment by Dindaleon** [comment]
It depends on what linting rules you are using. Are you using the ones that come with the project or your own?

**Comment by utvk** [comment]
just plain install, so i guess yours. e.g. missing semicolons. get errors like this:

error on server side: SyntaxError: hapi-react-starter-kit/src/themes/default/AppBar.js: A semicolon is required after a class property (78:3)

**Comment by Dindaleon** [comment]
Yes please add them. You are probably using babel 6.4 which does complain about missing semi colons after a class.

**Comment by utvk** [comment]
im only using projects from the package.json file? are you using a locally installed babel?

**Comment by Dindaleon** [comment]
I am using babel 6.3 that comes with the package.json 
Look at this: https://github.com/LKay/react-bootstrap-datetimepicker/pull/2

I am not getting those errors though.

**Comment by utvk** [comment]
yea, i guess you would get same problem when you do a npm update. I'll fix and push a pr. cool stack btw ;)

**Comment by Dindaleon** [comment]
great, thanks! Glad you like it.

**Comment by utvk** [comment]
yea, I like it a lot :) i'll see if i can use it for a project and help out a little. i didn't look into eslint rules, but i saw you raised issue on project regarding the semi color issue.

**Comment by Dindaleon** [comment]
Do you know about code testing with karma, mocha...? Since I updated to babel 6, tests are broken.

**Comment by utvk** [comment]
yes, i can take a look a little later

**Comment by utvk** [comment]
One thing i noticed, was that the react preset didnt load in the test. Can you add a .babelrc with this and try to run the tests?

{
  presets: ['es2015', 'react', 'stage-0']
}

I get some weird error still though that I dont understand. i havent used es6 exports, neither redux for react so would be good if you could look.. The error is "the request of a dependency is an expression", but im uncertain what is causing it.

**Comment by Dindaleon** [comment]
I spent a few days trying to fix and was not able to. I tried adding a `.babelrc` file. I also get that error. I have no idea what is causing it.
