### ISSUE TITLE
To do: Fix tests

### ISSUE THREAD

**Issue by Dindaleon** [Dindaleon/hapi-react-starter-kit#6]
Tests are currently broken.

**Comment by utvk** [comment]
I got them to work, but there were some issues:
1. you need the .babelrc file as mentioned on #13 
2. Index.spec.js reference src/components/Index.js that doesn't exist, so it will never run
3. Layout.spec.js doesn't provided required props and will fail
4. the children property in Layout. component is set as object but should be an array
5. The app and home tests were empty and didnt run

I pushed a test commit here that i managed to run: https://github.com/utvk/hapi-react-starter-kit/commit/81193c0c7b4a5649cd13f987a20a22b91f6d9beb

Note, this commit is only a test and I'm not sure how you want the tests or how you plan to implement them but they seems to run ok. except for this one weird error, that you hopefully can ignore

```
WARNING in ./src/themes/index.js
Critical dependencies:
91:69-145 the request of a dependency is an expression
 @ ./src/themes/index.js 91:69-145
22 01 2016 23:03:48.127:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
22 01 2016 23:03:48.137:INFO [launcher]: Starting browser Firefox
22 01 2016 23:03:49.831:INFO [Firefox 43.0.0 (Linux 0.0.0)]: Connected on socket /#OMVUPN9THfKIAc94AAAA with id 67756489
Firefox 43.0.0 (Linux 0.0.0) ERROR: 'Warning: Failed propType: Invalid prop `children` of type `array` supplied to `Locale`, expected `object`.'
  Components
    Layout
      ✔ should contain one <did> element with id="layout"
      ✔ should contain children

Finished in 0.118 secs / 0.001 secs

SUMMARY:
✔ 2 tests completed
```

**Comment by Dindaleon** [comment]
Excellent! I will take a look and commit.

**EDIT** fixed for next commit. Thank you @utvk you were right. The file `.babelrc` was needed. Somehow, karma won't take the babel configuration inside its config file.
