### ISSUE TITLE
Simplify dev and prod server

### ISSUE THREAD

**Issue by zebapy** [Dindaleon/hapi-react-starter-kit#7]
Seems a bit crazy that both the devserver and main server are nearly identical. Can they not be combined in some manner with simply using the globals to check what environment they are?

**Comment by Dindaleon** [comment]
Good advice, thanks. Next release will use only one `server` file.

**Comment by Dindaleon** [comment]
Solved in commit https://github.com/Dindaleon/hapi-react-starter-kit/commit/0af27f663b48ada23cbaa81d8928c8840125195d
